spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: user_service_app
    password: 12345
    driver-class-name: org.postgresql.Driver
app:
  jwt:
    secret: bc33dbc3-f28b-45f2-9b9a-af84ef39a676
    issuer: FinanceApp