server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/user_service
    username: user_service_app
    password: 12345
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
app:
  jwt:
    secret: bc33dbc3-f28b-45f2-9b9a-af84ef39a676
    issuer: FinanceApp