FROM eclipse-temurin:17-jre-focal

WORKDIR /usr/src/finance_management_classifier

COPY target/finance_management_classifier-1.0.0.jar /usr/src/finance_management_classifier/finance_management_classifier-1.0.0.jar

CMD ["java", "-jar", "/usr/src/finance_management_classifier/finance_management_classifier-1.0.0.jar"]
