FROM eclipse-temurin:17-jre-focal

WORKDIR /usr/src/finance_management_audit

COPY target/finance_management_audit-1.0.0.jar /usr/src/finance_management_audit/finance_management_audit-1.0.0.jar

CMD ["java", "-jar", "/usr/src/finance_management_audit/finance_management_audit-1.0.0.jar"]
