version: '3.8'

services:
  swagger:
    build: ./swagger-ui
    image: swagger-finance:1.0.0
    ports:
      - 81:8080
    networks:
      - finance-network

  pg_db:
    build: ./postgresql
    image: postgresql-finance:1.0.0
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 123
    networks:
      - finance-network

  pgadmin:
    build: ./pgadmin
    image: pgadmin-finance:1.0.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 82:80
    networks:
      - finance-network

  proxy:
    build: ./proxy
    image: proxy_finance:1.0.0
    ports:
      - 80:80
    networks:
      - finance-network

  finance-management-user:
    build: ./finance_management_user
    image: user-service:1.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: user_service_app
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - finance-network

  finance-management-classifier:
    build: ./finance_management_classifier
    image: classifier-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: classifier_service_app
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - finance-network

  finance-management-account:
    build: ./finance_management_account
    image: account-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: account_service_app
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - finance-network

  finance-management-audit:
    build: ./finance_management_audit
    image: audit-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: audit_service_app
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - finance-network

networks:
  finance-network: