server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service
    username: audit_service_app
    password: 12345
    driver-class-name: org.postgresql.Driver
app:
  jwt:
    secret: bc33dbc3-f28b-45f2-9b9a-af84ef39a676
    issuer: FinanceApp
  audit-client:
    url: http://localhost:8083/audit
  user-client:
    url: http://localhost:8080