server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service
    username: audit_service_app
    password: 12345
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
app:
  jwt:
    secret: bc33dbc3-f28b-45f2-9b9a-af84ef39a676
    issuer: FinanceApp
  user-client:
    url: http://localhost:8080/cabinet/me
  audit-client:
    url: http://localhost:8080/audit
  user-audit-client:
    url: http://localhost:8080/users/{uuid}