FROM eclipse-temurin:17-jre-focal

WORKDIR /usr/src/finance_management_account

COPY target/finance_management_account-1.0.0.jar /usr/src/finance_management_account/finance_management_account-1.0.0.jar

CMD ["java", "-jar", "/usr/src/finance_management_account/finance_management_account-1.0.0.jar"]
