server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/account_service
    username: account_service_app
    password: 12345
    driver-class-name: org.postgresql.Driver
app:
  jwt:
    secret: bc33dbc3-f28b-45f2-9b9a-af84ef39a676
    issuer: FinanceApp
  user-client:
    url: http://finance-management-user:8080/cabinet/me
  audit-client:
    url: http://finance-management-audit:8080/audit
  category-client:
    url: http://finance-management-classifier:8080/classifier/operation/category
  currency-client:
    url: http://finance-management-classifier:8080/classifier/currency