FROM openjdk:17

WORKDIR /usr/src/finance_management_user

COPY target/finance_management_user-1.0.0.jar /usr/src/finance_management_user/finance_management_user-1.0.0.jar

CMD ["java", "-jar", "/usr/src/finance_management_user/finance_management_user-1.0.0.jar"]