server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classifier_service
    username: classifier_service_app
    password: 12345
    driver-class-name: org.postgresql.Driver
app:
  jwt:
    secret: bc33dbc3-f28b-45f2-9b9a-af84ef39a676
    issuer: FinanceApp
  user-client:
      url: http://localhost:8080/cabinet/me
  audit-client:
      url: http://localhost:8083/audit